version: 2
updates:
  - package-ecosystem: "npm"
    target-branch: "master"
    versioning-strategy: "increase"
    directory: "/packages/cache-memory"
    schedule:
      interval: "weekly"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
            - "minor"
            - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
            - "minor"
            - "patch"
    rebase-strategy: "auto"
  - package-ecosystem: "npm"
    target-branch: "master"
    versioning-strategy: "increase"
    directory: "/packages/featureserver"
    schedule:
      interval: "weekly"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
            - "minor"
            - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
            - "minor"
            - "patch"
    rebase-strategy: "auto"
  - package-ecosystem: "npm"
    target-branch: "master"
    versioning-strategy: "increase"
    directory: "/packages/core"
    schedule:
      interval: "weekly"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
            - "minor"
            - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
            - "minor"
            - "patch"
    rebase-strategy: "auto"
  - package-ecosystem: "npm"
    target-branch: "master"
    versioning-strategy: "increase"
    directory: "/packages/logger"
    schedule:
      interval: "weekly"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
            - "minor"
            - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
            - "minor"
            - "patch"
    rebase-strategy: "auto"
  - package-ecosystem: "npm"
    target-branch: "master"
    versioning-strategy: "increase"
    directory: "/packages/output-geoservices"
    schedule:
      interval: "weekly"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
            - "minor"
            - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
            - "minor"
            - "patch"
    rebase-strategy: "auto"
  - package-ecosystem: "npm"
    target-branch: "master"
    versioning-strategy: "increase"
    directory: "/packages/winnow"
    schedule:
      interval: "weekly"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
            - "minor"
            - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
            - "minor"
            - "patch"
    rebase-strategy: "auto"
  - package-ecosystem: "npm"
    target-branch: "master"
    versioning-strategy: "increase"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
            - "minor"
            - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
            - "minor"
            - "patch"
    rebase-strategy: "auto"
